#!/usr/bin/env python3
"""
build_index.py — Generate corpus-level navigation from a pdf2md manifest.

Writes two files into the Markdown output directory:

  README.md  — corpus overview: what this is, coverage stats, how to ingest it
  INDEX.md   — every talk, grouped by conference, linked, with speakers

A 611-document tree is hard for an agent to explore blind. The index gives it a
single cheap file to read first to find out what exists, and the README states
the conversion caveats (OCR confidence, image-only slides) up front so anything
consuming the corpus knows what it is holding.

Usage:
    python3 tools/build_index.py --out markdown
"""

from __future__ import annotations

import argparse
import collections
import json
import os
import urllib.parse


def load(manifest: str) -> list[dict]:
    records = []
    with open(manifest, "r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                records.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    return records


def link(path: str) -> str:
    return urllib.parse.quote(path)


def conf_sort_key(name: str, recs: list[dict]) -> tuple:
    years = [r.get("year") for r in recs if r.get("year")]
    return (-(max(years) if years else 0), name)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default="markdown", help="Markdown corpus directory")
    ap.add_argument("--manifest", default="", help="defaults to <out>/manifest.jsonl")
    args = ap.parse_args()

    out_root = os.path.abspath(args.out)
    manifest = args.manifest or os.path.join(out_root, "manifest.jsonl")
    if not os.path.exists(manifest):
        print(f"No manifest at {manifest}; run tools/pdf2md.py first.")
        return 1

    records = [r for r in load(manifest) if r.get("status") == "ok"]
    failed = [r for r in load(manifest) if r.get("status") != "ok"]
    if not records:
        print("Manifest contains no successful conversions.")
        return 1

    groups: dict[str, list[dict]] = collections.defaultdict(list)
    for rec in records:
        groups[rec.get("conference_full") or rec.get("source_folder") or "Other"].append(rec)

    total_pages = sum(r.get("pages", 0) for r in records)
    total_chars = sum(r.get("text_chars", 0) for r in records)
    total_ocr = sum(r.get("ocr_pages", 0) for r in records)
    ocr_docs = sum(1 for r in records if r.get("ocr_pages"))
    order = sorted(groups, key=lambda k: conf_sort_key(k, groups[k]))

    # ---------------- INDEX.md ----------------
    idx = ["# Talk index", "",
           f"{len(records)} talks across {len(groups)} conference editions. "
           f"Generated from `manifest.jsonl`.", ""]
    for conf in order:
        recs = sorted(groups[conf], key=lambda r: r.get("title", "").lower())
        idx.append(f"## {conf}  ({len(recs)} talks)")
        idx.append("")
        for r in recs:
            speakers = ", ".join(r.get("speakers") or []) or "—"
            flag = f" · OCR {r['ocr_pages']}p" if r.get("ocr_pages") else ""
            idx.append(f"- [{r.get('title', '(untitled)')}]({link(r['markdown'])}) — "
                       f"{speakers} · {r.get('pages', 0)}pp{flag}")
        idx.append("")
    with open(os.path.join(out_root, "INDEX.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(idx))

    # ---------------- README.md ----------------
    rows = []
    for conf in order:
        recs = groups[conf]
        rows.append(
            f"| {conf} | {len(recs)} | {sum(r.get('pages', 0) for r in recs):,} | "
            f"{sum(r.get('text_chars', 0) for r in recs):,} | "
            f"{sum(r.get('ocr_pages', 0) for r in recs):,} |")

    readme = [
        "# Security conference talks — Markdown corpus",
        "",
        "Machine-readable Markdown converted from the conference slide decks in "
        "this repository. Built for retrieval and LLM ingestion: one file per "
        "talk, YAML frontmatter for filtering, `## Slide N` headings as natural "
        "chunk boundaries.",
        "",
        "Generated by [`tools/pdf2md.py`](../tools/pdf2md.py). "
        "See [`tools/README.md`](../tools/README.md) for the conversion design "
        "and its trade-offs.",
        "",
        "## Corpus at a glance",
        "",
        f"- **{len(records)} talks** across **{len(groups)} conference editions**",
        f"- **{total_pages:,} slides**",
        f"- **{total_chars:,} characters** of extracted text (~{total_chars // 4:,} tokens)",
        f"- **{total_ocr:,} slides** recovered by OCR across {ocr_docs} decks that a "
        "text-only extractor would have dropped",
        "",
        "| Conference | Talks | Slides | Characters | OCR slides |",
        "|---|---:|---:|---:|---:|",
        *rows,
        "",
        "## Files",
        "",
        "- `INDEX.md` — every talk, grouped by conference, with speakers and links",
        "- `manifest.jsonl` — one JSON record per talk; drive ingestion from this",
        "- `<Conference Folder>/<slug>.md` — the converted talks",
        "",
        "## Ingesting this corpus",
        "",
        "Each file opens with YAML frontmatter:",
        "",
        "```yaml",
        "title: \"...\"",
        "speakers: [\"...\"]",
        "conference: \"Black Hat\"      # series, normalised across spellings",
        "conference_full: \"Black Hat USA 2026\"",
        "year: 2026",
        "source_pdf: \"...\"            # provenance, exact source file",
        "sha256: \"...\"                # detects upstream changes",
        "pages: 58",
        "ocr_pages: 55                 # how much of this doc is OCR-confidence",
        "has_ocr: true",
        "```",
        "",
        "Two things worth doing at ingest time:",
        "",
        "1. **Split on `## Slide N` headings, not character counts.** Slides are the "
        "natural semantic unit; fixed-size chunking cuts mid-thought.",
        "2. **Copy the frontmatter into every chunk's metadata.** Frontmatter is "
        "stripped by most splitters, and without it a chunk loses the conference, "
        "year and speaker that make it filterable.",
        "",
        "## Reading the output honestly",
        "",
        "- Text inside a fenced block preceded by *\"recovered by OCR\"* came from "
        "Tesseract reading a slide image. It is approximate — identifiers, flags "
        "and hex values may be wrong. Treat it as a retrieval signal, and verify "
        "against `source_pdf` before quoting it as fact.",
        "- A bare `## Slide N` with no body is a slide whose entire content was a "
        "photograph or diagram with no text. Nothing was lost in conversion; there "
        "was no text to extract. Recovering the meaning of those slides needs a "
        "vision model (see `tools/README.md`).",
        "- Slide decks are supporting material for a spoken talk. They carry the "
        "technical substance but not the narration, so gaps in argument are "
        "expected.",
        "",
    ]
    if failed:
        readme += ["## Conversion failures", "",
                   f"{len(failed)} source files did not convert:", ""]
        readme += [f"- `{r['source_pdf']}` — {r.get('status')}: "
                   f"{r.get('error', '')[:120]}" for r in failed[:40]]
        readme += [""]

    with open(os.path.join(out_root, "README.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(readme))

    print(f"Wrote {os.path.join(out_root, 'README.md')}")
    print(f"Wrote {os.path.join(out_root, 'INDEX.md')}")
    print(f"  {len(records)} talks, {total_pages:,} slides, {total_chars:,} chars, "
          f"{total_ocr:,} OCR slides, {len(failed)} failures")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
